[project]
authors = ["Seth Stadick <sstadick@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge",
]
name = "ish"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
build-bench = "magic run mojo build --march native -I /home/ubuntu/dev/ExtraMojo -I ./ishlib -o ish-aligner ./ish_bench_aligner.mojo"
build = "magic run mojo build -I /home/ubuntu/dev/ExtraMojo -o ish main.mojo"
pkglib = "magic run mojo package -I /home/ubuntu/dev/ExtraMojo ./ishlib"
testlib = "magic run mojo test -I ./ishlib ./tests"

[dependencies]
max = "=25.1.0"
# extramojo = ">=0.9.0,<0.10"
