[project]
authors = ["Seth Stadick <sstadick@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge",
]
name = "ish"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
build = "pixi run mojo build -D ISH_LOG_LEVEL=info --march native -o ish main.mojo"
debug = "pixi run mojo build -D ISH_LOG_LEVEL=debug --debug-level line-tables --march native -o ish main.mojo"
pkglib = "pixi run mojo package ./ishlib"
testlib = "pixi run mojo test -I ishlib --co && pixi run mojo test -I ishlib"

# Bench the gpu fun in ish using Bench
build-bench-gpu = "pixi run mojo build -D ISH_LOG_LEVEL=timing --march native -I ./ishlib -o bench-gpu ./ish_bench_aligner_gpu_only.mojo"

# Bench any algorithm using internal timings
build-bench = "pixi run mojo build -D SIMD_MOD=1 --march native  -I ./ishlib -o ish-aligner ./ish_bench_aligner.mojo"
build-bench-128 = "pixi run mojo build -D SIMD_MOD=4 --march native  -I ./ishlib -o ish-aligner-128 ./ish_bench_aligner.mojo"
build-bench-256 = "pixi run mojo build -D SIMD_MOD=2 --march native  -I ./ishlib -o ish-aligner-256 ./ish_bench_aligner.mojo"
build-bench-512 = "pixi run mojo build -D SIMD_MOD=1 --march native  -I ./ishlib -o ish-aligner-512 ./ish_bench_aligner.mojo"
build-bench-gpu-all = "pixi run mojo build -D ISH_LOG_LEVEL=timing -D SIMD_MOD=1 --march native  -I ./ishlib -o ish-aligner-gpu ./ish_bench_aligner_gpu.mojo"

[dependencies]
max = "=25.3.0"
zlib = ">=1.3.1,<2"
extramojo = "=0.14.0"
